export const AirTimePricing = [
  {
    name: 'Basic',
    id: '953',
    href: '#',
    price: 'SSP 80',
    validity: '1 hour',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'Basic+',
    id: '943',
    href: '#',
    price: 'SSP 500',
    validity: '1 day',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'Flex',
    id: '944',
    href: '#',
    price: 'SSP 1200',
    validity: '3 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'Pro',
    id: '966',
    href: '#',
    price: 'SSP 2500',
    validity: '7 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'Max',
    id: '962',
    href: '#',
    price: 'SSP 9000',
    validity: '30 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
]

export const MoMoPricing = [
  {
    name: 'MOMO Basic',
    id: '1074',
    href: '#',
    price: 'SSP 80',
    validity: '1 hour',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'MOMO Basic+',
    id: '1075',
    href: '#',
    price: 'SSP 500',
    validity: '1 day',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'MOMO Flex',
    id: '1076',
    href: '#',
    price: 'SSP 1200',
    validity: '3 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'MOMO Pro',
    id: '1077',
    href: '#',
    price: 'SSP 2500',
    validity: '7 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  {
    name: 'MOMO Max',
    id: '1078',
    href: '#',
    price: 'SSP 9000',
    validity: '30 days',
    description: '',
    features: ['Unlimited HD movies', 'Stream from laptop, phone, tablet and smart TVs',],
  },
  
]